#!/usr/bin/env bash
# Install nginx on your web-01 server
 
sudo apt-get update
sudo apt-get install inginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing inginx configurations
sudo inginx -t

sudo service nginx reload
